language: java

sudo: false
cache:
  directories:
      - $HOME/.m2

before_script: '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && printf "org.killbill.billing.plugin.adyen.merchantAccount=${ADYEN_MERCHANT_ACCOUNT}\\norg.killbill.billing.plugin.adyen.username=${ADYEN_USERNAME}\\norg.killbill.billing.plugin.adyen.password=${ADYEN_PASSWORD}\\norg.killbill.billing.plugin.adyen.paymentUrl=${ADYEN_PAYMENT_URL}\\norg.killbill.billing.plugin.adyen.hmac.secret=${ADYEN_HMAC_SECRET}\\norg.killbill.billing.plugin.adyen.skin=${ADYEN_SKIN}\\norg.killbill.billing.plugin.adyen.hpp.target=${ADYEN_HPP_TARGET}\\n" > src/test/resources/adyen.properties'
after_script: rm -f src/test/resources/adyen.properties
script: if [[ -v COMMAND ]]; then $COMMAND; else travis_retry mvn clean install $PHASE | egrep -v 'Download|Install'; [ ${PIPESTATUS[0]} == 0 ]; fi
# Remove --quiet to avoid timeouts
install: mvn -U install -DskipTests=true | egrep -v 'Download|Install'

notifications:
  email:
    - kill-bill-commits@googlegroups.com

env:
  global:
    - MAVEN_OPTS="-Xmx512m -XX:MaxPermSize=192m"

matrix:
  allow_failures:
    - jdk: oraclejdk8
  include:
    - env: PHASE="-Ptravis"
      jdk: openjdk7
    - env: PHASE="-Ptravis"
      jdk: oraclejdk7
    - env: PHASE="-Ptravis,jdk17"
      jdk: openjdk7
    - env: PHASE="-Ptravis,jdk17"
      jdk: oraclejdk7
    - env: PHASE="-Ptravis,jdk18"
      jdk: oraclejdk8
  fast_finish: true

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && echo "<settings><servers><server><id>sonatype-nexus-snapshots</id><username>\${env.OSSRH_USER}</username><password>\${env.OSSRH_PASS}</password></server></servers></settings>" > ~/settings.xml && travis_wait mvn deploy -DskipTests=true --settings ~/settings.xml | egrep -v "Download|Install|Upload" ; rm -f ~/settings.xml'
